version: '2'
services:
  firefly-gone-plaid:
    container_name: firefly-gone-plaid
    image: hothamandcheese/firefly-gone-plaid
    build:
      context: .      
    restart: unless-stopped
    volumes:
      - ./config:/config
